yatube/posts/urls.py
from django.urls import path

from . import views

# Эта строчка обязательна.
# Без нее чуда не произойдет и namespace работать не будет
app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main-view'),
    path('index/', views.index, name='main-view'),
    path('index.html', views.index, name='main-view'),
    path('group/<slug:slug>', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

yatube/posts/models.py
import textwrap as tw

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


User = get_user_model()


class Post(models.Model):
    text = models.TextField('Текст')
    pub_date = models.DateTimeField('Дата', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        related_name='groups',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа'
    )

    class Meta:
        db_table = 'posts'
        ordering = ('-pub_date', 'author',)
        indexes = (
            models.Index(fields=['author'], name='author_idx'),
            models.Index(fields=['text'], name='search_text_idx'),
        )

    def __str__(self):
        # Обрезает тест до длины, меньшей или равной 40-и,
        # между границами слов, чтобы не было частичных слов.
        return tw.shorten(self.text, 40, placeholder='...')


class Group(models.Model):
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField('Подзаголовок', max_length=200, unique=True)
    description = models.TextField('Описание', default='', blank=True)

    class Meta:
        db_table = 'groups'
        ordering = ('title',)
        indexes = (models.Index(fields=['title'], name='title_idx'),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        # Получаю url из posts/urls.py по имени.
        return reverse('posts:group_list', kwargs={'slug': self.slug})

yatube/posts/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Group, Post


def index(request: HttpRequest) -> HttpResponse:
    """Main page. """
    temp = 'posts/index.html'
    title = 'Последние обновления на сайте'
    posts = Post.objects.all()[:10]
    context = {
        'title': title,
        'posts': posts,
    }
    return render(request, temp, context)


def group_posts(request: HttpRequest, slug: str) -> HttpResponse:
    """View-функция для страницы сообщества. """
    group = get_object_or_404(Group, slug=slug)
    temp = 'posts/group_list.html'
    title = f'Записи сообщества {group.title}'
    posts = group.groups.all()[:10]
    context = {
        'title': title,
        'group': group,
        'posts': posts,
    }
    return render(request, temp, context)

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static "img/fav/favicon.ico" %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "img/fav/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "img/fav/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "img/fav/favicon-16x16.png" %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <title>{{ title }}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}    
    </header>
    <main>
      {% block content %}
        Base content
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html> 

yatube/templates/includes/footer.html
{% load static %}
<p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'posts:main-view' %}">
      <img src="{% static "img/logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
      <span style="color:red">Ya</span>tube</a>
    </a>
  </div>
</nav>

yatube/templates/post/group_list.html
{% extends 'base.html' %}
{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in posts %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>    
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock %}

yatube/templates/post/index.html
{% extends 'base.html' %}
{% block content %}
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">     
    <h1>Последние обновления на сайте</h1>
    {% for post in posts %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      <!-- Проверяю есть ли группа у поста, и если есть отображаю url -->
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    <!-- под последним постом нет линии -->
  </div> 
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>
      {{ group.description }}
    </p>
    {% for post in posts %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>    
      </article>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="container py-5">     
    <h1>Последние обновления на сайте</h1>
    {% for post in posts %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>{{ post.text }}</p>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div> 
{% endblock %}